@NSE.Identidade.API_HostAddress = https://localhost:7061

GET {{NSE.Identidade.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{NSE.Identidade.API_HostAddress}}/api/identidade/nova-conta
Content-Type: application/json

{
  "email": "sid@test.com",
  "senha": "Teste@123",
  "senhaconfirmacao": "Teste@123"
}

###
